name: CI
on:
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile
      - name: Build
        uses: actions/upload-artifact@v2
        with:
          name: build-${{ github.sha }}
          path: .

  lint:
    needs: [build]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build-${{ github.sha }}
      - run: make lint

  prettier:
    needs: [build]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build-${{ github.sha }}
      - run: make prettier

  test:
    needs: [build]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build-${{ github.sha }}
      - run: make test
