name: CI/CD
env:
  ORG: rdok
  NAME: weathcast
  HEROKU_AUTH_TOKEN: ${{ secrets.HEROKU_API_KEY }}
  PIPELINE: weathcast
on:
  push:
    branches: [ main, dev ]
  workflow_dispatch:
    inputs:
      environment:
        required: false
        description: "Allowed values: prod, test"
        default: prod
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Prepare environment variables
        id: env
        env:
          ENVIRONMENT: ${{ github.event.inputs.environment }}
        run: |
          [ "$ENVIRONMENT" = "" ] && ENVIRONMENT=test
          echo ::set-output name=app::"${ORG}-${ENVIRONMENT}-${NAME}"

          if [ "$ENVIRONMENT" == "test" ]; then
            echo "TODO: add test envs."
          elif [ "$ENVIRONMENT" == "prod" ]; then
            echo "TODO: add prod envs."
          else
            printf '%s\n' "ENVIRONMENT is not in accepted range: test, prod." >&2
            exit 1
          fi
      - name: Lint, Prettier & Test
        run: |
          yarn install --frozen-lockfile
          make lint
          make prettier
          make test
      - name: Heroku Login
        run: |
          sed --in-place --expression \
            "s/{{HEROKU_AUTH_TOKEN}}/${HEROKU_AUTH_TOKEN}/g" \
            .github/workflows/.netrc
          mv .github/workflows/.netrc ~/
      - name: Prepare deployment
        run: |
          git checkout -b ${{ github.head_ref }}
          heroku apps:create --region eu ${{ steps.env.outputs.app }} || true
          heroku config:set --app=${{ steps.env.outputs.app }} YARN_PRODUCTION=true
          heroku git:remote --app=${{ steps.env.outputs.app }}
      - name: Deploy
        run: |
          git push heroku ${{ github.head_ref }}:main --force
          heroku ps:scale web=1
      - name: Cleanup
        if: always()
        run: rm --force ~/.netrc
